### ISSUE TITLE
Execution stoped

### ISSUE THREAD

**Issue by martiadrogue** [datacharmer/test_db#10]
Hi,
When I try to create the database the script stops showing the following message

```
ERROR at line 113: Failed to open file 'load_departments.dump', error: 2
```

I'm following the steps from README.md, and when I call `mysql < employees.sql` I see the error.
I'm using an Ubuntu 14.04, the vagrant box is minimal/trusty64. And the mysql is the default, it's installed following next commands

```
sudo apt-get update
sudo apt-get install mysql-server
sudo mysql_secure_installation
sudo mysql_install_db
```

So, the version is:

```
mysql  Ver 14.14 Distrib 5.5.61, for debian-linux-gnu (x86_64) using readline 6.3
```

Thanks

**Comment by datacharmer** [comment]
Please see Issue #9.
Did you change directory after downloading the repo?
