### ISSUE TITLE
Loading employees.sql requires undocumented RELOAD privilege

### ISSUE THREAD

**Issue by kolbe** [datacharmer/test_db#13]
employees.sql includes the line `flush /*!50503 binary */ logs;`. `FLUSH LOGS` requires the `RELOAD` privilege, which means that a user with normal privileges, following the instructions in README.md, will be unable to load the database.

Solutions:

1) Get rid of the `flush logs` line. Why is it there in the first place? What's the point of flushing logs as part of an unrelated data import operation?
2) Add `-f` to invocations of the mysql command-line client so that it will continue executing even if an error is encountered.
3) Document the need for the `RELOAD` privilege in README.md.

**Comment by datacharmer** [comment]
Thanks for spotting the issue.
I have update the README with the needed privileges.
