### ISSUE TITLE
specifying column orders for .dump files

### ISSUE THREAD

**Issue by kaestro** [datacharmer/test_db#22]
Thank you for providing us with such nice database sample. I appreciate it.

While I was following the tutorial from the oracle mysql-connector-python, I had trouble executing the **load_dept_manager.dump** for the **order of columns didn't match with the table I've made** .

**I fixed it with specifying the column order** by changing into

INSERT INTO `dept_manager`(emp_no, dept_no, from_date, to_date) VALUES 
(110022,'d001','1985-01-01','1991-10-01'),
...

and it worked well.

I know its really a minor problem that most will be able to handle, but I think it could help a lot for those who might be even newbier than I am.

Thank you.

**Comment by datacharmer** [comment]
This change can be done.
However, I would like to understand the problem better. What situation causes a failure? How can I reproduce it?

**Comment by kaestro** [comment]
I was following tutorial given from mysql
https://dev.mysql.com/doc/connector-python/en/connector-python-example-ddl.html

Here, creating table was not in order with the load data

```python
TABLES['dept_manager'] = (
    "  CREATE TABLE `dept_manager` ("
    "  `dept_no` char(4) NOT NULL,"
    "  `emp_no` int(11) NOT NULL,"
    "  `from_date` date NOT NULL,"
    "  `to_date` date NOT NULL,"
    "  PRIMARY KEY (`emp_no`,`dept_no`),"
    "  KEY `emp_no` (`emp_no`),"
    "  KEY `dept_no` (`dept_no`),"
    "  CONSTRAINT `dept_manager_ibfk_1` FOREIGN KEY (`emp_no`) "
    "     REFERENCES `employees` (`emp_no`) ON DELETE CASCADE,"
    "  CONSTRAINT `dept_manager_ibfk_2` FOREIGN KEY (`dept_no`) "
    "     REFERENCES `departments` (`dept_no`) ON DELETE CASCADE"
    ") ENGINE=InnoDB")
```

After I've created table with this, I **used mysql workbench** to **run the scripts.**

Every other dumps worked except for dept_manager.

But to be safe, **I think adding column names to other dumps also could help too!**

I'm sorry that my explanation could be insufficient for I haven't raised any issues before.

If there's any more information you need, I want to be of help.

Thank you.

**Comment by datacharmer** [comment]
So, the problem is that the tutorial authors didn't copy the data structure correctly, and did not test the procedure that they suggest.

I filed [bug#99746](https://bugs.mysql.com/bug.php?id=99746) about this issue.

While the improvement suggested is legitimate, and eventually I will get it done, I think it would be easier changing two lines in the tutorial instead of 168 lines in the `test_db` code.

**Comment by kaestro** [comment]
I haven't thought about talking to the tutorial writer.

Thank you for giving me the better solution.

I'll try to reach them about this too.

**Comment by datacharmer** [comment]
It has been fixed.

**Comment by kaestro** [comment]
Thank you!
