### ISSUE TITLE
Replacing the deprected 'source' in employees.sql

### ISSUE THREAD

**Issue by boardtc** [datacharmer/test_db#35]
My understanding is that source has been deprecated for some years.

However, https://github.com/datacharmer/test_db/blob/master/employees.sql includes:
SELECT 'LOADING departments' as 'INFO';
source load_departments.dump ;

In Workbench source is underlined in red and gives the error:  "source is not valid at this position"

I can run the different dump files individually but these scripts should not include an error/bug. 

Is there an alternative to using source,

Bizarrely this was reported over 2 years ago: https://forums.mysql.com/read.php?10,685467,685502

**Comment by datacharmer** [comment]
Could you provide me with the information about deprecating `source`?
As far as I know, it is still a valid command (https://dev.mysql.com/doc/refman/8.0/en/mysql-batch-commands.html)
Sorry about the forums: I don't actively read them, and I was not noticed when the issue was reported.

**Comment by boardtc** [comment]
Thanks for the reply. Your link indicated it's valid for the command line. I am talking about opening the sql file in the sql editor and executing it there. 'Source' shows as red in the editor, like [this](![image](https://user-images.githubusercontent.com/214808/193853666-079f4d82-b7e8-4aa7-b213-450e987b914f.png))
Does that make sense?

**Comment by datacharmer** [comment]
Sorry, I am a command-line guy, and I don't know anything about the SQL editor you mention.If it is a feature of MySQL Workbench, you should ask them.
Consider, however, that I am certainly not going to make the test_db unusable from the command line to accommodate the needs of a visual tool. My first consideration is to preserve the usability for early adopter of this database.

**Comment by boardtc** [comment]
Oh, sorry, I opened this in the wrong place, I did not realise, sorry.

**Comment by datacharmer** [comment]
The SQL file is perfectly valid, when used with the MySQL command line shell. It has been so since 2008 (that's 14 years of compatibility).
If MySQL Workbench used to work with it and now it doesn't, it was their decision, which should not affect how other projects work.

**Comment by boardtc** [comment]
To close this out they closed [108694](https://bugs.mysql.com/bug.php?id=108694) as a duplicate of [63999](https://bugs.mysql.com/bug.php?id=63999) which was opened over 10 years ago.

**Comment by christianblueskylabs** [comment]
I ended up on this repo from a [slow query log article](https://cloud.google.com/community/tutorials/stackdriver-monitor-slow-query-mysql) from Google Cloud as seen under **Generate sample data with a load test** to test if the flags are working.

I'm also encountering the issue explained at hand. I'm running a GCP Cloud SQL on MySQL 8.0.26 and I am unable to just simply load employees.sql.

Appreciate the effort into researching on this, @boardtc. For time-travelers in the future who might read this, simply follow the suggestion on manually loading the dump files in the order they are shown in employees.sql.
