### ISSUE TITLE
Hitting an error during the sql script run

### ISSUE THREAD

**Issue by toufiqalamau** [datacharmer/test_db#4]
08:44:34	set storage_engine = InnoDB	Error Code: 1193. Unknown system variable 'storage_engine'	0.000 sec

When I run the 'employees.sql' I am getting this error. This is happening to all of the scripts. I am using MySql workbench the latest.

How do I make it work?

I am getting this warning as well:

action: DROP TABLE IF EXISTS dept_emp,  dept_manager, titles, salaries, employees, departments

message:
0 row(s) affected, 6 warning(s): 1051 Unknown table 'employees.dept_emp' 1051 Unknown table 'employees.dept_manager' 1051 Unknown table 'employees.titles' 1051 Unknown table 'employees.salaries' 1051 Unknown table 'employees.employees' 1051 Unknown table 'employees.departments'

Would please tell me why is it happening? I am a novice learner. So, I do not know many details. 
Thanks.

**Comment by datacharmer** [comment]
You are apparently using am old version of the repository from Launchpad. Please get the latest code from this repository and try again.

The warning on "DROP TABLE IF EXISTS" is expected.
