### ISSUE TITLE
Error during "Run SQL Script"

### ISSUE THREAD

**Issue by keilybmason** [datacharmer/test_db#43]
While attempting to run the script, "employees.scrpt" I received the following error: Error during "Run SQL Script" error calling Python module function SQLIDEUtils.runSQLScript. I don't believe the instructor mentioned Python during his installation for MySQL Workbench for Microsoft. 

How is this issue corrected?

Thank you!

**Comment by datacharmer** [comment]
My instructions refer to operations on the command line (Unix shell). If you get a Python error, it is due to whatever tool you are using for the installation instead of the command line

**Comment by keilybmason** [comment]
I figured out my issue. Thank you very much for responding. When I uninstalled and reinstalled the program, the Python issue went away. Thanks again.
