### ISSUE TITLE
Unknown storage engine 'blackhole' , [windows10 xampp]

### ISSUE THREAD

**Issue by pavanyogi** [datacharmer/test_db#7]
E:\git_programs\test_db (master -> origin)
λ mysql -u root -p -t < test_employees_md5.sql
Enter password:
+----------------------+
| INFO                 |
+----------------------+
| TESTING INSTALLATION |
+----------------------+
+--------------+------------------+----------------------------------+
| table_name   | expected_records | expected_crc                     |
+--------------+------------------+----------------------------------+
| employees    |           300024 | 4ec56ab5ba37218d187cf6ab09ce1aa1 |
| departments  |                9 | d1af5e170d2d1591d776d5638d71fc5f |
| dept_manager |               24 | 8720e2f0853ac9096b689c14664f847e |
| dept_emp     |           331603 | ccf6fe516f990bdaa49713fc478701b7 |
| titles       |           443308 | bfa016c472df68e70a03facafa1bc0a8 |
| salaries     |          2844047 | fd220654e95aea1b169624ffe3fca934 |
+--------------+------------------+----------------------------------+
ERROR 1286 (42000) at line 58: Unknown storage engine 'blackhole'

E:\git_programs\test_db (master -> origin)

**Comment by datacharmer** [comment]
Check your MySQL and make sure that the blackhole engine is enabled.

    select * from information_schema.engines where engine="blackhole"\G
    *************************** 1. row ***************************
          ENGINE: BLACKHOLE
         SUPPORT: YES
         COMMENT: /dev/null storage engine (anything you write to it disappears)
    TRANSACTIONS: NO
              XA: NO
      SAVEPOINTS: NO
    1 row in set (0.00 sec)

**Comment by jy95** [comment]
For people that uses MariaDb : 

> The BLACKHOLE Storage Engine was enabled by default until MariaDB 10.0. From MariaDB 10.1, the plugin needs to be specifically enabled

https://mariadb.com/kb/en/library/blackhole/

**Comment by kekkosan** [comment]
Unfortunately, this is a known Bug in Xampp (and many more distributions), a problem between MariaDB and phpMyAdmin. The most easy solution would be, to install an older Xampp release. Or, if you want to keep you Xampp installation, the next most easy fix is just to create the missing folder c:/xampp/mysql/lib/plugin

There are of course more sophisticated workarounds, but these are getting more and more difficult. I would not go for a difficult solution, as long as i am not an Xampp expert.
