### ISSUE TITLE
ERROR at line 113: Failed to open file 'load_departments.dump', error: 2

### ISSUE THREAD

**Issue by dunhanson** [datacharmer/test_db#9]
ERROR at line 113: Failed to open file 'load_departments.dump', error: 2

**Comment by dunhanson** [comment]
😂Already solved, I did not switch directories

**Comment by martiadrogue** [comment]
Mmmmm, This sold my problem :+1:

**Comment by thewesleyee** [comment]
Hello, 
May I know which directory you switched to? I switched to the directory that held the repository but i got the exact same error as you while running that code. 
Please help. 
![1](https://user-images.githubusercontent.com/29250909/49315971-b2dd2a80-f4ef-11e8-9195-625501f570fb.JPG)

**Comment by sercuto** [comment]
I had the same problem.
You need to change to folder root

**Comment by electronart** [comment]
Also occurs from MySQL Workbench.

**Comment by datacharmer** [comment]
> Also occurs from MySQL Workbench.

Please see the answers above.
You need to run `cd employees` and then import the SQL file.

**Comment by Harsh-Vrdhn** [comment]
Hello, i'm trying to open the database in my sql workbench but is unable to do so. I have just started learning sql so i don't have much knowledge about it and hence i'm unable to solve the issue myself someone please help me out. 
![Screenshot (35)](https://github.com/user-attachments/assets/bf09489d-364c-4102-a489-373192bd62aa)

**Comment by ShivamNimbalkar** [comment]
> Hello, i'm trying to open the database in my sql workbench but is unable to do so. I have just started learning sql so i don't have much knowledge about it and hence i'm unable to solve the issue myself someone please help me out. ![Screenshot (35)](https://github.com/user-attachments/assets/bf09489d-364c-4102-a489-373192bd62aa)

Just Change all the  Source Location to your local source in employees.sql
check the below ss as i change the default source destination to my local onces.

![Image](https://github.com/user-attachments/assets/1dc89f6b-fd8c-4ebf-b417-ebd2f9a27cd0)
